<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<?php $tablica[] = $this->liczby; ?>
<table>
    <tr>
        <td>
            Parzyste
        </td>
        <td>
            Nieparzyste
        </td>
    </tr>
    <tr>
        <td>
            <?php
            foreach($tablica[0][0] as $value){
                echo $value.', ';
            }
            ?>
        </td>
        <td>
            <?php
            foreach($tablica[0][1] as $value){
            echo $value.', ';}
            ?>
        </td>
    </tr>
</table>
</body>
</html>
